// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

namespace Server.Migrations
{
    [DbContext(typeof(WebAPIDBContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");
                modelBuilder.Entity("Server.Models.Content", b =>
                {
                    b.Property<string>("Filename")
                        .HasColumnType("TEXT");
                    b.Property<string>("TotalChunks")
                        .HasColumnType("INTEGER");
                    b.Property<string>("Data")
                        .HasColumnType("TEXT");
                    b.Property<string>("ChunksLoaded")
                        .HasColumnType("INTEGER");
                    b.Property<string>("Time")
                        .HasColumnType("TEXT");
                    b.HasKey("Filename");
                    b.ToTable("Content");
                });
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");
                modelBuilder.Entity("Server.Models.EventContent", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");
                    b.Property<string>("Event")
                        .HasColumnType("TEXT");
                    b.HasKey("Event");
                    b.ToTable("EventContent");
                });
#pragma warning restore 612, 618
        }
    }
}
